### ISSUE TITLE
Server crashes after some time 

### ISSUE THREAD

**Issue by sylbru** [guillaumebrunerie/dixit-elixir#12]
The server crashes some times when it is not used, possibly because of too many crashes of a process in a few seconds:

> Note that the supervisor that reaches maximum restart intensity will exit with :shutdown reason. In this case the supervisor will only be restarted if its child specification was defined with the :restart option set to :permanent (the default).

In our case it seems it’s because of a few random queries (probably intended to hurt us).

```
08:21:49.674 pid=<0.769.0> [info]  Hello from a player
08:21:49.674 pid=<0.769.0> [debug] :recv "HEAD / HTTP/1.0"
08:21:49.674 pid=<0.769.0> [warn]  Unknown header: HEAD / HTTP/1.0
08:21:49.674 pid=<0.769.0> [debug] :recv ""
08:21:49.674 pid=<0.760.0> [error] Task #PID<0.760.0> started from Dixit.MainSupervisor terminating
** (MatchError) no match of right hand side value: {:error, {:badarg, [{Dixit.Player, :"-handshake/2-fun-1-", 1, [file: 'lib/player.ex', line: 100]}, {Dixit.Player, :handshake, 2, [file: 'lib/player.ex', line: 100]}, {Dixit.Player, :init, 1, [file: 'lib/player.ex', line: 21]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 417]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 385]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
    (dixit 0.1.0) lib/networklistener.ex:36: Dixit.NetworkListener.loop_acceptor/2
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Dixit.NetworkListener.listen/1
    Args: [[port: 4020, ws?: true]]
08:21:49.675 pid=<0.770.0> [info]  Accepting connections on port 4020 (WebSockets)
08:21:49.675 pid=<0.771.0> [info]  Accepting connections on port 4000 (plain text)
08:21:50.392 pid=<0.772.0> [info]  Hello from a player
08:21:50.392 pid=<0.772.0> [debug] :recv "GET /system_api.php HTTP/1.1"
08:21:50.392 pid=<0.772.0> [warn]  Unknown header: GET /system_api.php HTTP/1.1
08:21:50.392 pid=<0.772.0> [debug] :recv "Host: 54.38.184.182:4020"
08:21:50.392 pid=<0.772.0> [debug] :recv "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
08:21:50.392 pid=<0.772.0> [debug] :recv "Accept-Encoding: gzip, deflate"
08:21:50.392 pid=<0.772.0> [debug] :recv "Accept: */*"
08:21:50.392 pid=<0.772.0> [debug] :recv "Connection: keep-alive"
08:21:50.392 pid=<0.772.0> [warn]  Unknown header: Connection: keep-alive
08:21:50.392 pid=<0.772.0> [debug] :recv ""
08:21:50.393 pid=<0.770.0> [error] Task #PID<0.770.0> started from Dixit.MainSupervisor terminating
** (MatchError) no match of right hand side value: {:error, {:badarg, [{Dixit.Player, :"-handshake/2-fun-1-", 1, [file: 'lib/player.ex', line: 100]}, {Dixit.Player, :handshake, 2, [file: 'lib/player.ex', line: 100]}, {Dixit.Player, :init, 1, [file: 'lib/player.ex', line: 21]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 417]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 385]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
    (dixit 0.1.0) lib/networklistener.ex:36: Dixit.NetworkListener.loop_acceptor/2
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Dixit.NetworkListener.listen/1
    Args: [[port: 4020, ws?: true]]
08:21:50.394 pid=<0.773.0> [info]  Accepting connections on port 4020 (WebSockets)
08:21:50.394 pid=<0.774.0> [info]  Accepting connections on port 4000 (plain text)
08:21:50.811 pid=<0.775.0> [info]  Hello from a player
08:21:50.811 pid=<0.775.0> [debug] :recv "GET /system_api.php HTTP/1.1"
08:21:50.811 pid=<0.775.0> [warn]  Unknown header: GET /system_api.php HTTP/1.1
08:21:50.811 pid=<0.775.0> [debug] :recv "Host: 54.38.184.182:4020"
08:21:50.811 pid=<0.775.0> [debug] :recv "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
08:21:50.811 pid=<0.775.0> [debug] :recv "Accept-Encoding: gzip, deflate"
08:21:50.812 pid=<0.775.0> [debug] :recv "Accept: */*"
08:21:50.812 pid=<0.775.0> [debug] :recv "Connection: keep-alive"
08:21:50.812 pid=<0.775.0> [warn]  Unknown header: Connection: keep-alive
08:21:50.812 pid=<0.775.0> [debug] :recv ""
08:21:50.812 pid=<0.773.0> [error] Task #PID<0.773.0> started from Dixit.MainSupervisor terminating
** (MatchError) no match of right hand side value: {:error, {:badarg, [{Dixit.Player, :"-handshake/2-fun-1-", 1, [file: 'lib/player.ex', line: 100]}, {Dixit.Player, :handshake, 2, [file: 'lib/player.ex', line: 100]}, {Dixit.Player, :init, 1, [file: 'lib/player.ex', line: 21]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 417]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 385]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
    (dixit 0.1.0) lib/networklistener.ex:36: Dixit.NetworkListener.loop_acceptor/2
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Dixit.NetworkListener.listen/1
    Args: [[port: 4020, ws?: true]]
08:21:50.813 pid=<0.776.0> [info]  Accepting connections on port 4020 (WebSockets)
08:21:50.813 pid=<0.777.0> [info]  Accepting connections on port 4000 (plain text)
08:21:51.229 pid=<0.778.0> [info]  Hello from a player
08:21:51.229 pid=<0.778.0> [debug] :recv "GET /c/version.js HTTP/1.1"
08:21:51.229 pid=<0.778.0> [warn]  Unknown header: GET /c/version.js HTTP/1.1
08:21:51.229 pid=<0.778.0> [debug] :recv "Host: 54.38.184.182:4020"
08:21:51.229 pid=<0.778.0> [debug] :recv "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
08:21:51.229 pid=<0.778.0> [debug] :recv "Accept-Encoding: gzip, deflate"
08:21:51.230 pid=<0.778.0> [debug] :recv "Accept: */*"
08:21:51.230 pid=<0.778.0> [debug] :recv "Connection: keep-alive"
08:21:51.230 pid=<0.778.0> [warn]  Unknown header: Connection: keep-alive
08:21:51.230 pid=<0.778.0> [debug] :recv ""
08:21:51.230 pid=<0.776.0> [error] Task #PID<0.776.0> started from Dixit.MainSupervisor terminating
** (MatchError) no match of right hand side value: {:error, {:badarg, [{Dixit.Player, :"-handshake/2-fun-1-", 1, [file: 'lib/player.ex', line: 100]}, {Dixit.Player, :handshake, 2, [file: 'lib/player.ex', line: 100]}, {Dixit.Player, :init, 1, [file: 'lib/player.ex', line: 21]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 417]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 385]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
    (dixit 0.1.0) lib/networklistener.ex:36: Dixit.NetworkListener.loop_acceptor/2
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Dixit.NetworkListener.listen/1
    Args: [[port: 4020, ws?: true]]
08:21:51.232 pid=<0.568.0> [info]  Application dixit exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,dixit,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,dixit,shutdown})

Crash dump is being written to: erl_crash.dump...done
```

**Comment by sylbru** [comment]
:+1:
